# Generated by Django 6.0.4 on 2026-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_notification_action_type_postcommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chapter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
