# Generated by Django 6.0.4 on 2026-05-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='post_audio/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('QUOTE', 'Quote'), ('OPINION', 'Opinion'), ('UPDATE', 'Reading Update'), ('AUDIO', 'Audio Bite')], default='UPDATE', max_length=20),
        ),
    ]
