# Generated by Django 6.0.4 on 2026-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_post_post_type_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('LIKE', 'New Like'), ('COMMENT', 'New Comment'), ('NEW_BOOK', 'New Book'), ('FOLLOW', 'New Follower'), ('SYSTEM', 'System Message'), ('POST_LIKE', 'New Post Like'), ('POST_COMMENT', 'New Post Comment'), ('REPOST', 'New Repost'), ('POST_COMMENT_LIKE', 'New Post Comment Like'), ('NEW_CHAPTER', 'New Chapter'), ('MILESTONE', 'Achievement Unlocked'), ('TRENDING', 'Trending Alert'), ('STREAK_REMINDER', 'Streak Protection'), ('POLL_RESULT', 'Poll Results Available')], max_length=20),
        ),
    ]
