# Generated by Django 6.0.4 on 2026-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='status',
            field=models.CharField(choices=[('TO_READ', 'To Read'), ('READING', 'Currently Reading'), ('FINISHED', 'Finished')], default='TO_READ', max_length=20),
        ),
    ]
