# Generated by Django 6.0.4 on 2026-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userlibrary_is_favorite_userlibrary_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('audio_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
