# Generated by Django 6.0.4 on 2026-05-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended_ambient_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ambientsound'),
        ),
    ]
