# Generated by Django 6.0.4 on 2026-05-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_recommended_ambient_sound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAmbientSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(default='🎵', max_length=10)),
                ('audio_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='readingprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userlibrary',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='core_book_title_119b07_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='core_book_slug_5e0421_idx',
        ),
        migrations.RenameField(
            model_name='ambientsound',
            old_name='is_active',
            new_name='is_system',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='stripe_checkout_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='readingprogress',
            old_name='updated_at',
            new_name='last_read',
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'book')},
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='page_index',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='status',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='shelf',
            field=models.CharField(choices=[('TO_READ', 'To Read'), ('READING', 'Reading'), ('FINISHED', 'Finished')], default='TO_READ', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambientsound',
            name='emoji',
            field=models.CharField(default='🎵', max_length=10),
        ),
        migrations.AlterField(
            model_name='ambientsound',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='chapter_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readstats',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.book'),
        ),
        migrations.AlterField(
            model_name='readstats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userambientsound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='book',
            name='region',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transaction_id',
        ),
        migrations.AlterUniqueTogether(
            name='userambientsound',
            unique_together={('user', 'name')},
        ),
    ]
