# Generated by Django 6.0.4 on 2026-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userambientsound_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userambientsound',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='userambientsound',
            name='audio_file',
            field=models.FileField(default='', upload_to='user_ambient/'),
            preserve_default=False,
        ),
    ]
