# Generated by Django 6.0.4 on 2026-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_userambientsound_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientsound',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='ambient_sounds/'),
        ),
        migrations.AlterField(
            model_name='ambientsound',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
